import Navbar from "@/components/navbar"
import "../styles/global.css"

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
