import Navbar from "@/components/navbar"
import "../styles/global.css"
import localFont from "next/font/local"

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by Next.js',
}

const pixelatedFont = localFont({
  src: "../fonts/04B_03__.ttf",
  display: "swap",
})

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <div className={pixelatedFont.className}>
          <Navbar/>
          {children}
        </div>
      </body>
    </html>
  )
}
